### ISSUE TITLE
Discord bot token directly in source code

### ISSUE THREAD

**Issue by GioSDA** [BurgBoi/TSKManagerBot#1]
Hello! In your Main class, you directly have your token. This is not recommended, as at any time, someone could visit this repository and hijack your bot! I'd recommend keeping it in a file, or adding the token as an argument from the command line. However you do it, try and remove the token from the source code and delete previous commits.

**Comment by BurgBoi** [comment]
Oh, that bot token isn't valid. I'm just too lazy to clean that up.
